name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 'v22.14.0'
        - name: Install Dependencies
          run: npm install

        - name: Test
          run: npm run wdio

        - name: Upload Logs
          uses: actions/upload-artifact@v4
          if: failure()
          with:
            name: logs
            path: logs